name: Trunk Check
on:
  push:
    branches: [master]

permissions: read-all

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  trunk_check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
          arguments: --github-annotate-new-only=false
